# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uAKuPTDOwsX5Y6yeoHer_aS5r2VzaaGt
"""

import numpy as np
import matplotlib.pyplot as plt

# Parametri
LM_fixed = 4
alpha = 0.188

G_dB_values = np.arange(110, 141, 5)
pout_targets = [0.25, 0.10, 0.05, 0.01]
labels = ['25%', '10%', '5%', '1%']

def K_from_margin(M_dB):
    return (np.log(10) / 10) * M_dB

def pout_circ(sigma, G, K, alpha=0.188):
    x = K / (2 * sigma**2 * alpha * G)
    return (1 + x) * np.exp(-x)

def bisection_circ(G, M_dB, pout_target, alpha=0.188, tol=1e-15):
    K = K_from_margin(M_dB)
    a, b = 1e-9, 1e-3
    for _ in range(100):
        mid = (a + b) / 2
        if pout_circ(mid, G, K, alpha) > pout_target:
            b = mid
        else:
            a = mid
        if (b - a) < tol:
            break
    return (a + b) / 2

# Tabella
print(f"{'G [dB]':<10}", end='')
for p in labels:
    print(f"{p:>12}", end='')
print()

for G_dB in G_dB_values:
    G = 10**(G_dB / 10)
    print(f"{G_dB:<10.2f}", end='')
    for p in pout_targets:
        s = bisection_circ(G, LM_fixed, p) * 1e6
        print(f"{s:>12.3f}", end='')
    print()

plt.figure(figsize=(10, 6))
for p, lbl in zip(pout_targets, labels):
    sigma_vals = [bisection_circ(10**(G_dB/10), LM_fixed, p) * 1e6
                  for G_dB in G_dB_values]
    plt.plot(G_dB_values, sigma_vals, marker='o', label=f'$P_{{out}}$ = {lbl}')

plt.xlabel('Guadagno d\'antenna G [dB]')
plt.ylabel(r'$\sigma_{\theta,\max}$ [$\mu$rad]')
plt.legend(frameon=False)
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()