# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rCZjvRjRxCL6Y_05GcZm-bFjeqy4r3gX
"""

import numpy as np
from scipy.special import j1

# Parametri
LM_fixed = 4
G_dB_values = np.arange(110, 141, 5)
pout_targets = [0.25, 0.10, 0.05, 0.01]
labels = ['25%', '10%', '5%', '1%']

def K_from_margin(M_dB):
    return (np.log(10) / 10) * M_dB

def Lp_bessel(theta, G):
    x = np.sqrt(G) * theta
    return np.where(x == 0, 1.0, (2 * j1(x) / x) ** 2)

# Algoritmo 1
def pout_bessel(sigma, G, M_dB, N=5000):
    theta_max = 6 * sigma
    thetas = np.linspace(1e-10, theta_max, N)
    dt = thetas[1] - thetas[0]
    pmf = (thetas / sigma**2) * np.exp(-thetas**2 / (2*sigma**2)) * dt
    pmf = pmf / pmf.sum()

    Lp = Lp_bessel(thetas, G)
    loss_dB = -10 * np.log10(np.clip(Lp, 1e-10, 1.0))

    loss_t = loss_dB[:, np.newaxis]
    loss_r = loss_dB[np.newaxis, :]
    pmf_t = pmf[:, np.newaxis]
    pmf_r = pmf[np.newaxis, :]

    loss_tot = loss_t + loss_r
    pout = np.sum(pmf_t * pmf_r * (loss_tot > M_dB))
    return pout

def pout_gauss(sigma, G, K):
    x = K / (2 * sigma**2 * G)
    return (1 + x) * np.exp(-x)

def pout_circ_approx(sigma, G, K, alpha=0.188):
    x = K / (2 * sigma**2 * alpha * G)
    return (1 + x) * np.exp(-x)

def trova_sigma(pout_func, G, K, pout_target):
    a, b = 1e-9, 1e-3
    for _ in range(100):
        mid = (a + b) / 2
        if pout_func(mid, G, K) > pout_target:
            b = mid
        else:
            a = mid
    return (a + b) / 2

# Algoritmo 2
def bisection_bessel(G, M_dB, pout_target, tol=1e-8):
    K = K_from_margin(M_dB)
    sigma1 = trova_sigma(pout_gauss, G, K, pout_target)
    sigma2 = trova_sigma(pout_circ_approx, G, K, pout_target)

    for _ in range(50):
        mid = (sigma1 + sigma2) / 2
        if pout_bessel(mid, G, M_dB) > pout_target:
            sigma2 = mid
        else:
            sigma1 = mid
        if (sigma2 - sigma1) < tol:
            break
    return (sigma1 + sigma2) / 2

# Stampa tabella
print(f"{'G [dB]':<10}", end='')
for p in labels:
    print(f"{p:>12}", end='')
print()

for G_dB in G_dB_values:
    G = 10**(G_dB / 10)
    print(f"{G_dB:<10.2f}", end='')
    for p in pout_targets:
        s = bisection_bessel(G, LM_fixed, p) * 1e6
        print(f"{s:>12.3f}", end='')
    print()